= Scripting: De l'art d'écrire des scripts
Dhrions
Version 1.0.0, 12/01/2023
// Document attributes
:sectnums:                                                          
:toc:                                                   
:toclevels: 5  
:toc-title: Ma super table des matières
:icons: font

:description: Example AsciiDoc document                             
:keywords: AsciiDoc                                                 
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

// Mes variables
:url-wiki: https://fr.wikipedia.org/wiki
:url-wiki-Europe-Ouest: {url-wiki}/Europe_de_l%27Ouest

// This is the optional preamble (an untitled section body).
// Useful for writing simple sectionless documents consisting only of a preamble.

// NOTE:: Le mieux est d'écrire une phrase par ligne.

== Introduction

Sur Linux, on peut écrire des scripts dans les langages suivants sans procéder à une quelconque installation (en fonction du système d'exploitation) :

* *Bash* (Bourne Again Shell) : Bash est le *shell par défaut sur la plupart des distributions Linux*.
Il est spécialement conçu pour la création de scripts shell et est largement utilisé pour l'automatisation des tâches système.
* *Python* est un langage de programmation polyvalent et populaire.
Il est *préinstallé sur de nombreuses distributions Linux* et est utilisé pour une variété de tâches, y compris le _scripting_ système.

Il y a quelques règles à respecter propres à ces scripts :

* *Shebang* (en-tête du script) : Incluez une ligne de shebang au début du script pour indiquer quel interpréteur doit être utilisé pour exécuter le script. Par exemple, pour un script Bash, utilisez #!/bin/bash.
* Utilisation de chemins absolus et relatifs : Il est généralement recommandé d'utiliser des chemins absolus autant que possible dans les scripts pour éviter les problèmes liés au répertoire de travail en cours. Cependant, cela dépend du contexte. Parfois, l'utilisation de chemins relatifs peut être plus appropriée, surtout si le script doit être déplacé ou distribué.

== Bases

NOTE:: On considèrera que le script est un fichier qui se nomme `mon_script.sh`.

Le script le plus simple ressemble à cela :

[source, bash]
----
#!/bin/bash
----

Il s'agit d'un script qui indique seulement le _shebang_, c'est-à-dire le chemin de l'interpréteur à utiliser.
Aucune commande n'est exécutée.

D'autres _shebang_ peuvent être utilisés :

* `#!/bin/sh` : pour utiliser le shell par défaut ;
* `#!/bin/bash` : pour utiliser le shell Bash ;
* `#!/usr/bin/env python` : pour utiliser Python ;
* `#!/usr/bin/python3` : pour utiliser Python 3 ;
* etc.

On peut ensuite rajouter une commande très simple comme `echo` :

[source, bash]
----
#!/bin/bash
echo "Hello world!"
----

Pour exécuter le script, on peut utiliser l'une ou l'autre des deux méthodes suivantes :

[source, bash]
----
bash mon_script.sh
----

[source, bash]
----
chmod +x mon_script.sh
./mon_script.sh
----

== Comment transformer un script en commande

=== Rendre le fichier exécutable

Pour rendre un script exécutable pour tous les utilisateurs, il faut utiliser la commande `chmod` (change mode) :

[source, bash]
----
chmod +x ./mon_script.sh
----

=== Ajouter le script au PATH

Pour ajouter le script au PATH, il faut le copier dans un des répertoires du PATH.

Pour connaître le PATH, il faut utiliser la commande `echo` :

[source, bash]
----
echo $PATH
----

Cela peut donner :

[source, bash]
----
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
----

=== Ajouter le script au PATH (directement ou indirectement)

Pour ajouter le script au PATH, on doit le copier dans un des répertoires du PATH.

On note que 10 répertoires appartiennent au PATH :

* /usr/local/sbin
* /usr/local/bin
* /usr/sbin
* /usr/bin
* /sbin
* /bin
* /usr/games
* /usr/local/games
* /snap/bin
* /snap/bin

On va copier notre script dans un répertoire approprié.
Étant donné que notre script ne relève pas de Snap, on va exlure les répertoires commençant par `/snap`.
Étant donné que notre script ne relève pas de jeux, on va exlure les répertoires contenant `games`.
Étant donné que notre script ne concerne pas tous les utilisateurs, on va exclure les répertoires `/sbin` et `/bin` et privilégier ceux commençant par `/usr` (il nou reste alors `/usr/local/sbin`, `/usr/local/bin`, `/usr/sbin` et `/usr/bin`).
Étant donné que notre script ne concerne pas l'administration système, on exclut tous les répertoires contenant `sbin` (il nous reste alors `/usr/local/bin` et `/usr/bin`).

On peut ainsi l'ajouter à `/usr/local/bin` :

[source, bash]
----
sudo cp ./mon_script.sh /usr/local/bin/mon_script
----

=== Conclusion

On peut donc utiliser le script comme une commande en tapant :

[source, bash]
----
mon_script.sh
----

== Variables spéciales

On peut consulter https://www.it-connect.fr/les-variables-speciales-shell%EF%BB%BF/[cette page].

Il y a des variables spéciales qui permettent de récupérer certaines informations :

* `$0` : nom du script ;
* `$1` : premier argument ;
* `$2` : deuxième argument ;
* `$#` : contient le nombre total d'arguments passés au script ;
* `$*` : contient tous les arguments passés au script en tant que seule chaîne de caractères.

On peut écrire un script qui réunit toutes ces variables :

[source, bash]
----
#!/bin/bash
echo "Nom du script : $0"
echo "Premier argument : $1"
echo "Deuxième argument : $2"
echo "Nombre d arguments : $#"
echo "Chaîne des arguments : $*"
----

Ainsi, on peut exécuter :

[source, bash]
----
$ bash test.sh bleu blanc rouge
Nom du script : test.sh
Premier argument : bleu
Deuxième argument : blanc
Nombre d arguments : 3
Chaîne des arguments : bleu blanc rouge
----

== Les fonctions

On définit une fonction ainsi, en utilisant la _snake case_ :

[source, bash]
----
function hello_world() {
    echo "Hello world:"
}
----

On l'utilise ainsi :

[source, bash]
----
hello_world
----

On peut utiliser des arguments :

[source, bash]
----
function welcome() {
    echo "Tu t'appelles $1 et tu as $2 ans"
}

welcome "John" 32
----

Ainsi, on a :

[source, bash]
----
$ ./mon_script.sh
Tu t appelles John et tu as 32 ans
----
// === Listes ordonnées

// .Liste des pays :
// . Premier
// . Deuxième

// === Liste non ordonnées

// * item
// ** nested item
// * item
// * item
// * item
// ** nested item
// ** nested item
// *** subnested item
// ** nested item
// * item

// == Les citations

// // À propos des citations : https://docs.asciidoctor.org/asciidoc/latest/blocks/blockquotes/

// === Basic quote syntax

// [quote,attribution,citation title and information]
// Quote or excerpt text

// .After landing the cloaked Klingon bird of prey in Golden Gate park:
// [quote,Captain James T. Kirk,Star Trek IV: The Voyage Home]
// Everybody remember where we parked.

// === Quoted blocks

// [quote,Monty Python and the Holy Grail]
// ____
// Dennis: Come and see the violence inherent in the system. Help! Help! I'm being repressed!

// King Arthur: Bloody peasant!

// Dennis: Oh, what a giveaway! Did you hear that? Did you hear that, eh? That's what I'm on about! Did you see him repressing me? You saw him, Didn't you?
// ____

// === Quoted paragraphs

// "I hold it that a little rebellion now and then is a good thing,
// and as necessary in the political world as storms in the physical."
// -- Thomas Jefferson, Papers of Thomas Jefferson: Volume 11

// == Les liens

// Pour aller à la section intitulée « <<Les listes>> », c'est par <<Les listes, ici>>.

// Il y a un dossier intéressant : link:./example1[ici].

// == Les variables ({url-wiki-Europe-Ouest}[cf. Wikipédia])

// == Les blocs

// .Voici le titre d'un bloc
// Et là, cela est un bloc, constitué d'une phrase.
// Et d'une deuxième phrase.
// Et d'une troisième.

// == Le code

// [source, python]
// ----
// print("Hello world"!)
// ----

// Je peux facilement inclure une partie d'un fichier de code en-dessous.

// [source, python]
// ----
// include::./example1/python.py[tag=le-nom-de-mon-tag]
// ----

// CAUTION: `include` ne fonctionne pas sur Git Hub.