[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "make_linux_command"
version = "0.1"

[project.scripts]
make-linux-command = "make_linux_command.cli:cli"
