= Docker
Dhrions
Version 1.0.1, 19/01/2024
// Document attributes
:sectnums:                                                          
:toc:                                                   
:toclevels: 5  
:toc-title: Ma super table des matières
:icons: font

:description: Example AsciiDoc document                             
:keywords: AsciiDoc                                                 
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

// Mes variables
:url-wiki: https://fr.wikipedia.org/wiki
:url-wiki-Europe-Ouest: {url-wiki}/Europe_de_l%27Ouest

// This is the optional preamble (an untitled section body).
// Useful for writing simple sectionless documents consisting only of a preamble.

image::https://www.docker.com/wp-content/uploads/2023/08/logo-guide-logos-2.svg[Docker logo, 200]

On peut consulter https://openclassrooms.com/fr/courses/2035766-optimisez-votre-deploiement-en-creant-des-conteneurs-avec-docker[ce cours d'OpenClassrooms] pour plus d'informations.

== Docker

=== Commandes de base

On peut consulter https://openclassrooms.com/fr/courses/2035766-optimisez-votre-deploiement-en-creant-des-conteneurs-avec-docker/6211458-lancez-votre-premier-conteneur-en-local[ce chapitre d'OpenClassrooms] pour plus d'informations.

==== Lancer un conteneur

[source, bash]
----
docker run <image-name>
----

[source, bash]
----
docker run hello-world
----

==== Lancer un conteneur en arrière-plan

[source, bash]
----
docker run -d <image-name>
----

[source, bash]
----
docker run -d hello-world
----

==== Lancer un conteneur en arrière-plan avec un nom

[source, bash]
----
docker run -d --name <container-name> <image-name>
----

[source, bash]
----
docker run -d --name my-container nginx
----

==== Lancer un conteneur en arrière-plan avec un nom et un port

[source, bash]
----
docker run -d --name <container-name> -p <host-port>:<container-port> <image-name>
----

[source, bash]
----
docker run -d --name nginx -p 9999:80 nginx
----

==== Lancer un conteneur en arrière-plan avec un nom, un port et un volume

[source, bash]
----
docker run -d --name <container-name> -p <host-port>:<container-port> -v /chemin/machine/hote:/chemin/container/docker <image-name>
----

==== Lister les images locales

[source, bash]
----
docker image ls
----

==== Exécuter une commande dans un conteneur

[source, bash]
----
docker exec -it <container-name> <command>
----

[source, bash]
----
docker exec -it nextcloud sh
----

==== Copier le contenu d'un volume docker dans un dossier local

[source, bash]
----
docker cp nomduconteneur:/chemin/du/dossier /chemin/local
----

==== Supprimer tous les conteneurs, images, volumes et réseaux non utilisés

[source, bash]
----
docker system prune -a
----

== Dockerfile

On peut consulter https://openclassrooms.com/fr/courses/2035766-optimisez-votre-deploiement-en-creant-des-conteneurs-avec-docker/6211517-creez-votre-premier-dockerfile[ce chapitre d'OpenClassrooms] pour plus d'informations.

=== Pourquoi utiliser un Dockerfile en complément de Docker ?

Imaginons que l'on utilise un conteneur basé sur l'image `ubuntu` qui ne dispose pas de la commande `ping`.
On peut installer cette commande en exécutant la commande `apt-get install iputils-ping` dans le conteneur.
Toutefois, si l'on relance ce conteneur (ce qui peut arriver pour de multiples raisons), la commande `ping` ne sera plus disponible.
Or, si l'on veut qu'elle soit systématiquement disponible, il faut la réinstaller à chaque fois que l'on relance le conteneur.
Le Dockerfile permet de résoudre ce problème.
Il permet de créer une image personnalisée qui contient la commande `ping` et qui peut être utilisée pour créer un conteneur.

=== Usage

D'abord, on crée un fichier qui doit avoir pour nom `Dockerfile` (sans extension) dont le contenu peut-être le suivant :

[source, docker]
----
FROM ubuntu:latest
RUN apt-get update && apt-get install -y iputils-ping
----

Ensuite, on crée l'image `my-ubuntu` (on choisit le nom que l'on veut) à partir de ce Dockerfile en exécutant la commande suivante :

[source, bash]
----
docker build -t my-ubuntu .
----

On peut ensuite créer un conteneur à partir de cette image en exécutant la commande suivante :

[source, bash]
----
docker run -it my-ubuntu
----

=== Références

Il y a 18 différentes références d'un Dockerfile (cf. https://docs.docker.com/engine/reference/builder/[documentation officielle de Docker]) :

. *`FROM`* : l'image de base ;
. *`RUN`* : les commandes à exécuter ;
. *`CMD`* : les arguments de la commande à lancer.
. *`LABEL`* : les labels ;
. `MAINTAINER` (_deprecated_): le mainteneur ;
. *`EXPOSE`* : les ports à exposer ;
. *`ENV`* : les variables d'environnement ;
. *`ADD`* : les fichiers à ajouter ;
. *`COPY`* : les fichiers à copier ;
. `ENTRYPOINT` : la commande à lancer ;
. *`VOLUME`* : les volumes ;
. `USER` : l'utilisateur ;
. *`WORKDIR`* : le répertoire de travail ;
. `ARG` : les arguments ;
. `ONBUILD` : les commandes à exécuter lors de la construction d'une image enfant.
. `STOPSIGNAL` : le signal d'arrêt ;
. `HEALTHCHECK` : la commande de santé ;
. `SHELL` : le shell.

=== Principe sous-jacent

Chaque ligne d'un Dockerfile (sauf celle avec FROM) va créer une nouvelle couche.
Le système va ensuite créer une image à partir de ces couches.

Les couches peuvent resservir à la création d'autres images.

Ainsi, on considère le Dockerfile suivant :

[source, docker]
----
FROM ubuntu:latest
RUN apt-get update && apt-get install -y iputils-ping
----

Une couche est créée pour l'instruction `RUN`.

On crée ensuite le Dockerfile suivant :

[source, docker]
----
FROM ubuntu:latest
RUN apt-get update && apt-get install -y iputils-ping
RUN apt-get install -y curl
----

La couche pour la première instruction `RUN` existe déjà et n'a donc besoin d'être recréée (ce qui économise du temps de construction de l'image).
La couche pour la deuxième instruction `RUN` en revanche n'existe pas et doit donc être créée.

L'image créee à partir de ce Dockerfile est fabriquée à partir de deux couches.

En revanche, si l'on crée le Dockerfile suivant :

[source, docker]
----
FROM ubuntu:latest
RUN apt-get update && apt-get install -y iputils-ping && apt-get install -y curl
----

Une seule couche est créée pour l'instruction `RUN`.

== Docker Compose

=== Commandes de base

[source, bash]
----
# Lancer les services
docker-compose up

# Lancer les services en arrière-plan
docker-compose up -d

# Lancer un service en particulier
docker-compose up nomduservice

# Lancer un service en particulier en arrière-plan
docker-compose up -d nomduservice
----

=== Le fichier docker-compose.yml complet

Il y a 6 _top-level elements_ (cf. https://docs.docker.com/compose/compose-file/[documentation officielle de Docker Compose]) :

- `version` : la version de la syntaxe du fichier (cf. https://docs.docker.com/compose/compose-file/04-version-and-name/[documentation officielle de Docker Compose]) ;
- `services` : les services à lancer (cf. https://docs.docker.com/compose/compose-file/05-services/[documentation officielle de Docker Compose]);
- `networks` : les réseaux à créer (cf. https://docs.docker.com/compose/compose-file/06-networks/[documentation officielle de Docker Compose]);
- `volumes` : les volumes à créer ;
- `configs` : les fichiers de configuration à créer ;
- `secrets` : les secrets à créer.

Un seul _top-level element_ est obligatoire : `services` (cf. https://docs.docker.com/compose/compose-file/03-compose-file/[documentation officielle de Docker Compose]).

Les deux extraits de code suivants sont équivalents :

----
top-level-element:
    element1:
        sub-element1: "abcdefgh"
----

----
top-level-element:
    element1:
        sub-element1=abcdefgh
----

CAUTION:: Dans ce dernier cas, il faut veiller à ne pas mettre de guillemets autour de la valeur (il faut bien écrire `sub-element1=abcdefgh` et non `sub-element1="abcdefgh"`).
Cela peut être source de problèmes.

==== Version

==== Services

D'après https://docs.docker.com/compose/compose-file/05-services/[la documentation officielle de Docker Compose], il existe 83 attributs pour les services.
Parmi ceux-là, les deux plus importants sont :

. `image` : l'image à utiliser (cf. https://docs.docker.com/compose/compose-file/05-services/#image[documentation officielle de Docker Compose]) ;
. `build` : les options de build (cf. https://docs.docker.com/compose/compose-file/05-services/#build[documentation officielle de Docker Compose]).

NOTE:: En effet, pour construire un service, il faut utiliser une image.
Soit on utilise une image déjà existante (`image`), soit on construit une image (`build`).

Les autres attributs importants sont :

. `container_name` : le nom du conteneur (cf. https://docs.docker.com/compose/compose-file/05-services/#container_name[documentation officielle de Docker Compose]) ;
. `command` : la commande à lancer (cf. https://docs.docker.com/compose/compose-file/05-services/#command[documentation officielle de Docker Compose]) ;
. `environment` : les variables d'environnement (cf. https://docs.docker.com/compose/compose-file/05-services/#environment[documentation officielle de Docker Compose]) ;
. `ports` : les ports à exposer (cf. https://docs.docker.com/compose/compose-file/05-services/#ports[documentation officielle de Docker Compose]) ;
. `volumes` : les volumes à monter (cf. https://docs.docker.com/compose/compose-file/05-services/#volumes[documentation officielle de Docker Compose]) ;
. `networks` : les réseaux à utiliser (cf. https://docs.docker.com/compose/compose-file/05-services/#networks[documentation officielle de Docker Compose]) ;
. `depends_on` : les dépendances (cf. https://docs.docker.com/compose/compose-file/05-services/#depends_on[documentation officielle de Docker Compose]) ;
. `restart` : la politique de redémarrage (cf. https://docs.docker.com/compose/compose-file/05-services/#restart[documentation officielle de Docker Compose]) ;
. `labels` : les labels (cf. https://docs.docker.com/compose/compose-file/05-services/#labels[documentation officielle de Docker Compose]).

===== Networks

La rubrique `networks` du _top-level element_ `services` indique les paramètres réseaux du service considéré (cf. https://docs.docker.com/compose/compose-file/05-services/#networks[documentation officielle de Docker Compose]).

Un des attributs intéressants est `aliases` (cf. https://docs.docker.com/compose/compose-file/05-services/#aliases[documenation officielle]).
Il permet de donner un ou plusieurs noms d'hôte supplémentaires au conteneur considéré.

Ainsi, si l'on considère l'extrait de code suivant :

[source, yml]
----
services:
  some-service:
    container_name: mycontainer
    networks:
      some-network:
        aliases:
          - alias1
          - alias3
      other-network:
        aliases:
          - alias2
----

Si nous avons un autre conteneur sur le réseau `some-network`, il pourra pinguer le container `mycontainer` en tapant l'une des commandes suivantes :

[source, bash]
----
ping mycontainer
ping alias1
ping alias3
----

Si nous avons un autre conteneur sur le réseau `some-network`, il pourra pinguer le container `mycontainer` en tapant l'une des commandes suivantes :

[source, bash]
----
ping mycontainer
ping alias2
----

===== Secrets


==== Networks

D'après https://docs.docker.com/compose/compose-file/06-networks/#attachable[la documentation officielle de Docker Compose], il existe 9 attributs :

. `driver` : le driver du réseau (cf. https://docs.docker.com/compose/compose-file/06-networks/#driver[documentation officielle de Docker Compose]) ;
. `driver_opts` : les options du driver (cf. https://docs.docker.com/compose/compose-file/06-networks/#driver_opts[documentation officielle de Docker Compose]) ;
. `attachable` : si le réseau est attachable (cf. https://docs.docker.com/compose/compose-file/06-networks/#attachable[documentation officielle de Docker Compose]) ;
. `enable_ipv6` : si le réseau supporte l'IPv6 (cf. https://docs.docker.com/compose/compose-file/06-networks/#enable_ipv6[documentation officielle de Docker Compose]) ;
. `external` : si le réseau est externe (cf. https://docs.docker.com/compose/compose-file/06-networks/#external[documentation officielle de Docker Compose]) ;
. `ipam` : les options du driver IPAM (cf. https://docs.docker.com/compose/compose-file/06-networks/#ipam[documentation officielle de Docker Compose]) ;
. `internal` : si le réseau est interne (cf. https://docs.docker.com/compose/compose-file/06-networks/#internal[documentation officielle de Docker Compose]) ;
. `labels` : les labels du réseau (cf. https://docs.docker.com/compose/compose-file/06-networks/#labels[documentation officielle de Docker Compose]) ;
. `name` : le nom du réseau (cf. https://docs.docker.com/compose/compose-file/06-networks/#name[documentation officielle de Docker Compose]).

==== Volumes

==== Configs

==== Secrets