= Commandes
Dhrions
Version 1.1.0, 01/01/2024
// Document attributes
:sectnums:                                                          
:toc:                                                   
:toclevels: 5  
:toc-title: Ma super table des matières
:icons: font

:description: Example AsciiDoc document                             
:keywords: AsciiDoc                                                 
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

// Mes variables
:url-wiki: https://fr.wikipedia.org/wiki
:url-wiki-Europe-Ouest: {url-wiki}/Europe_de_l%27Ouest

On pourra consulter certaines pages dédiées à certaines commandes :

* link:./xargs/README.adoc[xargs] ;
* link:./date/README.adoc[date].

== Exécuter deux commandes d'affilée si la première a réussi

[source, bash]
----
command1 && command2
----

== Afficher le contenu d'un fichier entre deux lignes

[source, bash]
----
cat file | sed -n '4,45p'
----

== Afficher certaines colonnes d'une sortie

La commande suivante permet d'affficher la 2e, la 3e et la dernière colonne de la sortie de la commande `date`.

[source, bash]
----
date | awk '{print $2, $3, $NF}'
----

CAUTION: Il est important d'utiliser les simples guillemets. Avec les doubles guillemets, l'intégralité de la ligne serait affichée.

== Chercher un fichier

[source, bash]
----
find ./ -name "*.page" -type f -print0
----

La commande permet de trouver les fichiers (`-type f`) dont le nom termine par `.page` (`-name "*.page"`), dans le dossier courant (`./`) en n'interprétant pas les espaces comme la fin du nom du fichier (`-print0`).

== Afficher le contenu d'un CSV (awk ultime)

Voici le contenu de fichier.txt :

[source,bash]
----
A1;B1;C1;D1;10
A2;B2;C2;D2;1
A3;B3;C3;D3;10
----

Pour afficher :

- une en-tête ;
- la deuxième et la dernière colonne et seulement pour les lignes pour lesquelles la dernière colonne est supérieure à 10 ;
- un pied ;
- en précisant que le délimiteur d'entrée est `;` et celui de sortie `,`.

[source,bash]
----
awk -F";" 'BEGIN {OFS=","; print "En-tete\n--------"} $NF >= 10 {print $2, $NF} END {print "----------\nPied"}' test.txt
----

== Extraire les lignes avec des adresses IP

[source, bash]
----
grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' fichier.txt
----

== Lister les connexions actives

[source, bash]
----
netstat -tuln
----

[source, bash]
----
ss -tuln
----