= Expressions régulières

== Rappels

[headers]
|===
|\w  | Matches any alphanumeric character from the basic Latin alphabet, including the underscore. Equivalent to [A-Za-z0-9_]. For example, /\w/ matches "a" in "apple", "5" in "$5.28", and "3" in "3D".
|\d  | Matches any digit (Arabic numeral). Equivalent to [0-9]. For example, /\d/ or /[0-9]/ matches "2" in "B2 is the suite number".
|\b  | Matches a word boundary. This is the position where a word character is not followed or preceded by another word-character, such as between a letter and a space. Note that a matched word boundary is not included in the match. In other words, the length of a matched word boundary is zero.
|===

== Liste d'expressions régulières utiles

=== Toutes les lettres, même les accentuées

[source]
----
/[A-Za-zÀ-ÿŒœ@]/gm
----

=== Adresses IP

==== Version simplifiée

[source]
----
/([0-9]{1,3}\.){3}[0-9]{1,3}/gm
----

Les adresses IP de la forme `192.168.1.2`, `10.42.5.3` et `8.8.8.8` sont récupérés.
Des formes non conformes comme `999.999.999.999` sont aussi récupérées.

==== Version complète

[source]
----
/((\b25[0-5]|\b2[0-4][0-9]|\b1)?[1-9]?[0-9])(\.((25[0-5]|2[0-4][0-9]|1)?[1-9]?[0-9])){2}(\.((25[0-5]|2[0-4][0-9]|1)?[1-9]?[0-9]))\b/gm
----

== Numéros de téléphone

[source]
----
/06(\s\d{2}){4}|06(\d{2}){4}|06(\.\d{2}){4}|06(\-\d{2}){4}/gm
----

Les numéros de la forme «06 XX XX XX XX», «06XXXXXXXX», «06-XX-XX-XX-XX» et «06.XX.XX.XX.XX» sont récupérés, même perdus dans du texte.

== URL

URL de la forme « www.loremipsum.fr ».

[source]
----
/\bw{3}\.\w*\.fr\b/gm
----

== Adresse MAC

[source]
----
/([0-9a-f]{2}:){5}[0-9a-f]{2}/gm
----
